name: Deploy VK Bot

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "~/bot_admin_vk/.git" ]; then
              rm -rf ~/bot_admin_vk
              git clone https://github.com{{ github.repository }}.git ~/bot_admin_vk
            fi
            
            cd ~/bot_admin_vk
            git fetch origin master
            git reset --hard origin master
            
            touch optica.db

            docker build -t vk_bot_image .
            
            docker stop vk_bot_container || true
            docker rm vk_bot_container || true
            
            docker run -d \
              --name vk_bot_container \
              --restart always \
              -e TOKEN="${{ secrets.TOKEN }}" \
              -e ADMIN_ID="${{ secrets.ADMIN_ID }}" \
              -e SALON_NAME="${{ secrets.SALON_NAME }}" \
              -v ~/bot_admin_vk/optica.db:/app/optica.db \
              vk_bot_image
